version: '3.8'  # Specify the version of Docker Compose

# Define reusable configurations
x-common-environment: &common-environment
  POSTGRES_NAME: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  db:
    image: postgres:17
    environment:
      <<: *common-environment
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80" 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    depends_on:
      - db  
    restart: unless-stopped

  prestart:
    build:
      context: .
    depends_on:
      - db
    environment:
      <<: *common-environment
    command: bash scripts/prestart.sh

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      <<: *common-environment
    depends_on:
      - db
      - prestart
    command: uv run manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        - path: .
          action: sync
          target: /app

        - path: ./pyproject.toml
          action: rebuild

  backend-test:
    build: .
    command: uv run manage.py test
    environment:
      <<: *common-environment
    depends_on:
      - db
      - prestart


volumes:
    postgres:
    pgadmin: