version: '3.8'  # Specify the version of Docker Compose

# Define reusable configurations
x-common-environment: &common-environment
  POSTGRES_NAME: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      <<: *common-environment

  prestart:
    container_name: prestart
    build: .
    depends_on:
      - db
    environment:
      <<: *common-environment
    command: bash scripts/prestart.sh

  backend:
    container_name: backend
    build: .
    command: uv run manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      <<: *common-environment
    depends_on:
      - db
      - prestart

    develop:
      backend:
        watch:  # This section indicates that this service should be watched
          paths:
            - ./  # Specify the path(s) to watch for changes

