# Generated by Django 5.1.2 on 2024-10-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("cover", models.URLField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("FR", "French"),
                            ("ES", "Spanish"),
                            ("DE", "German"),
                            ("IT", "Italian"),
                        ],
                        default="EN",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
